# Generated by Django 3.2.25 on 2025-12-27 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('masters', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='users.organization'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='party_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers_as_party', to='masters.ledger'),
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together={('organization', 'voucher_type', 'voucher_number')},
        ),
    ]
