# Generated by Django 3.2.25 on 2025-12-27 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20251227_1449'),
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reference_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voucher',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voucherdetail',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_details', to='masters.batch'),
        ),
        migrations.AddField(
            model_name='voucherdetail',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_details', to='masters.costcenter'),
        ),
        migrations.AddField(
            model_name='voucherdetail',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucherdetail',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='voucherdetail',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_details', to='masters.warehouse'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('RECEIPT', 'Receipt'), ('PAYMENT', 'Payment'), ('CONTRA', 'Contra'), ('JOURNAL', 'Journal'), ('DEBIT_NOTE', 'Debit Note'), ('CREDIT_NOTE', 'Credit Note'), ('SALES_ORDER', 'Sales Order'), ('PURCHASE_ORDER', 'Purchase Order')], max_length=20),
        ),
    ]
